[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "PageUp"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "PageDown"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Alt"

[font]
size = 20

[font.bold]
family = "Ubuntu Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Ubuntu Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Ubuntu Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Ubuntu Mono Nerd Font"
style = "Regular"

[window]
opacity = 0.9

[general]
import = ["./catppuccin-mocha.toml"]

